### ISSUE TITLE
Support for WSL?

### ISSUE THREAD

**Issue by blink7** [AdRoll/hologram#100]
Is there possibility to run hologram-agent on the client-side machine using WSL (Ubuntu) in Windows 10?

**Comment by jammerful** [comment]
I also would like to get hologram-agent running under WSL2, I tried today but it seems like it crashes immediately after getting started:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5b0807]

goroutine 1 [running]:
panic(0x739400, 0xc42000c130)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
log/syslog.(*Writer).writeAndRetry(0x0, 0x6, 0xc420060840, 0x32, 0x0, 0x0, 0x0)
        /usr/local/go/src/log/syslog/syslog.go:245 +0x47
log/syslog.(*Writer).Info(0x0, 0xc420060840, 0x32, 0xc420060840, 0xc4200ae180)
        /usr/local/go/src/log/syslog/syslog.go:233 +0x48
github.com/AdRoll/hologram/log.(*syslogSink).Info(0xc420034050, 0xc420060840, 0x32)
        /go/src/github.com/AdRoll/hologram/log/syslog.go:39 +0x42
github.com/AdRoll/hologram/log.(*logMux).Info(0xc4200102a0, 0x7af669, 0x32, 0x0, 0x0, 0x0)
        /go/src/github.com/AdRoll/hologram/log/mux.go:50 +0xb5
github.com/AdRoll/hologram/log.Info(0x7af669, 0x32, 0x0, 0x0, 0x0)
        /go/src/github.com/AdRoll/hologram/log/log.go:79 +0xa0
main.main()
        /go/src/github.com/AdRoll/hologram/cmd/hologram-agent/main.go:120 +0x822
```

@blink7 Did you run into the same issue?
