### ISSUE TITLE
Sierra issues

### ISSUE THREAD

**Issue by copumpkin** [AdRoll/hologram#81]
#79 upgraded to Go 1.7.1, but that doesn't seem sufficient to fix our issues. It seemed to work at first, but after a while, I get stack traces in the agent along the lines of:

```
unexpected fault address 0x2ba94b6a6cfd
fatal error: fault
[signal 0xb code=0x1 addr=0x2ba94b6a6cfd pc=0x2ba94b6a6cfd]
goroutine 211 [running]:
runtime.gothrow(0x5364f0, 0x5)
	/usr/src/go/src/runtime/panic.go:503 +0x8e fp=0xc20805bbe0 sp=0xc20805bbc8
runtime.sigpanic()
	/usr/src/go/src/runtime/sigpanic_unix.go:29 +0x261 fp=0xc20805bc30 sp=0xc20805bbe0
created by net/http.(*Server).Serve
	/usr/src/go/src/net/http/server.go:1751 +0x35e
goroutine 1 [select, 59 minutes]:
main.main()
	/go/src/github.com/AdRoll/hologram/cmd/hologram-agent/main.go:122 +0x1376
goroutine 5 [syscall, 59 minutes]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35
goroutine 6 [IO wait]:
net.(*pollDesc).Wait(0xc208011250, 0x72, 0x0, 0x0)
	/usr/src/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208011250, 0x0, 0x0)
	/usr/src/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080111f0, 0x0, 0x8b0be0, 0xc2080d68a0)
	/usr/src/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20803c078, 0xc20805ddf8, 0x0, 0x0)
	/usr/src/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20803c078, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/tcpsock_posix.go:244 +0x4c
net/http.(*Server).Serve(0xc2080560c0, 0x8b2708, 0xc20803c078, 0x0, 0x0)
	/usr/src/go/src/net/http/server.go:1728 +0x92
net/http.Serve(0x8b2708, 0xc20803c078, 0x8b28d8, 0xc20800d950, 0x0, 0x0)
	/usr/src/go/src/net/http/server.go:1606 +0xa1
github.com/AdRoll/hologram/agent.(*metadataService).listen(0xc20801ec80)
	/go/src/github.com/AdRoll/hologram/agent/metadata_service.go:67 +0x3be
created by github.com/AdRoll/hologram/agent.(*metadataService).Start
	/go/src/github.com/AdRoll/hologram/agent/metadata_service.go:50 +0x44
goroutine 7 [IO wait, 58 minutes]:
net.(*pollDesc).Wait(0xc2080112c0, 0x72, 0x0, 0x0)
	/usr/src/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080112c0, 0x0, 0x0)
	/usr/src/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208011260, 0x0, 0x8b0be0, 0xc2080ba4b0)
	/usr/src/go/src/net/fd_unix.go:419 +0x40b
net.(*UnixListener).AcceptUnix(0xc20801ed40, 0x36aa0, 0x0, 0x0)
	/usr/src/go/src/net/unixsock_posix.go:282 +0x56
net.(*UnixListener).Accept(0xc20801ed40, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/unixsock_posix.go:293 +0x4c
github.com/AdRoll/hologram/transport/local.(*server).listen(0xc20801ed60)
	/go/src/github.com/AdRoll/hologram/transport/local/server.go:33 +0x4f
created by github.com/AdRoll/hologram/transport/local.NewServer
	/go/src/github.com/AdRoll/hologram/transport/local/server.go:65 +0x121
goroutine 11 [select, 58 minutes]:
net.func·019()
	/usr/src/go/src/net/dnsclient_unix.go:241 +0x2f4
created by net.loadConfig
	/usr/src/go/src/net/dnsclient_unix.go:269 +0x20c
```

**Comment by copumpkin** [comment]
Is nobody else seeing this behavior?

**Comment by copumpkin** [comment]
Ah, so I don't really know how Docker is supposed to work, but something is wonky with the current setup.

I added a call to `go version` to `start.sh` and sure enough, it says "go1.4.2".

Furthermore, when I tinker with the Dockerfile, the `hologram.sh` script doesn't seem to notice, so the script doesn't appear to be using the Dockerfile in the repository.

When I ran `docker rmi adroll/hologram_env` and it redownloaded the image, all was well and I was on 1.7.1.

**Comment by walterking** [comment]
does that solve the crash?  I've been running in sierra with no issues, but I dont use the docker build
